FROM httpd:2.4

ADD ./certificados/STAR_co.crt /usr/local/apache2/conf/STAR_co.crt
ADD ./certificados/STAR_co.key /usr/local/apache2/conf/STAR_co.key
ADD ./certificados/STAR_co.ca-bundle /usr/local/apache2/conf/STAR_co.ca-bundle
ADD ./conf/httpd.conf /usr/local/apache2/conf/httpd.conf
